=== api-evangelist/amazon-pinpoint/json-schema/amazon-pinpoint-update-recommender-configuration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-pinpoint/refs/heads/main/json-schema/amazon-pinpoint-update-recommender-configuration-schema.json",
  "title": "UpdateRecommenderConfiguration",
  "description": "Specifies Amazon Pinpoint configuration settings for retrieving and processing recommendation data from a recommender model.",
  "type": "object",
  "properties": {
    "Attributes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/MapOf__string"
        },
        {
          "description": "<p>A map of key-value pairs that defines 1-10 custom endpoint or user attributes, depending on the value for the RecommendationProviderIdType property. Each of these attributes temporarily stores a recommended item that's retrieved from the recommender model and sent to an AWS Lambda function for additional processing. Each attribute can be used as a message variable in a message template.</p> <p>In the map, the key is the name of a custom attribute and the value is a custom display name for that attribute. The display name appears in the <b>Attribute finder</b> of the template editor on the Amazon Pinpoint console. The following restrictions apply to these names:</p> <ul><li><p>An attribute name must start with a letter or number and it can contain up to 50 characters. The characters can be letters, numbers, underscores (_), or hyphens (-). Attribute names are case sensitive and must be unique.</p></li> <li><p>An attribute display name must start with a letter or number and it can contain up to 25 characters. The characters can be letters, numbers, spaces, underscores (_), or hyphens (-).</p></li></ul> <p>This object is required if the configuration invokes an AWS Lambda function (RecommendationTransformerUri) to process recommendation data. Otherwise, don't include this object in your request.</p>"
        }
      ]
    },
    "Description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "A custom description of the configuration for the recommender model. The description can contain up to 128 characters. The characters can be letters, numbers, spaces, or the following symbols: _ ; () , \u2010."
        }
      ]
    },
    "Name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "A custom name of the configuration for the recommender model. The name must start with a letter or number and it can contain up to 128 characters. The characters can be letters, numbers, spaces, underscores (_), or hyphens (-)."
        }
      ]
    },
    "RecommendationProviderIdType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "<p>The type of Amazon Pinpoint ID to associate with unique user IDs in the recommender model. This value enables the model to use attribute and event data that\u2019s specific to a particular endpoint or user in an Amazon Pinpoint application. Valid values are:</p> <ul><li><p>PINPOINT_ENDPOINT_ID - Associate each user in the model with a particular endpoint in Amazon Pinpoint. The data is correlated based on endpoint IDs in Amazon Pinpoint. This is the default value.</p></li> <li><p>PINPOINT_USER_ID - Associate each user in the model with a particular user and endpoint in Amazon Pinpoint. The data is correlated based on user IDs in Amazon Pinpoint. If you specify this value, an endpoint definition in Amazon Pinpoint has to specify both a user ID (UserId) and an endpoint ID. Otherwise, messages won\u2019t be sent to the user's endpoint.</p></li></ul>"
        }
      ]
    },
    "RecommendationProviderRoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the AWS Identity and Access Management (IAM) role that authorizes Amazon Pinpoint to retrieve recommendation data from the recommender model."
        }
      ]
    },
    "RecommendationProviderUri": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the recommender model to retrieve recommendation data from. This value must match the ARN of an Amazon Personalize campaign."
        }
      ]
    },
    "RecommendationTransformerUri": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The name or Amazon Resource Name (ARN) of the AWS Lambda function to invoke for additional processing of recommendation data that's retrieved from the recommender model."
        }
      ]
    },
    "RecommendationsDisplayName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "<p>A custom display name for the standard endpoint or user attribute (RecommendationItems) that temporarily stores recommended items for each endpoint or user, depending on the value for the RecommendationProviderIdType property. This value is required if the configuration doesn't invoke an AWS Lambda function (RecommendationTransformerUri) to perform additional processing of recommendation data.</p> <p>This name appears in the <b>Attribute finder</b> of the template editor on the Amazon Pinpoint console. The name can contain up to 25 characters. The characters can be letters, numbers, spaces, underscores (_), or hyphens (-). These restrictions don't apply to attribute values.</p>"
        }
      ]
    },
    "RecommendationsPerMessage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integer"
        },
        {
          "description": "<p>The number of recommended items to retrieve from the model for each endpoint or user, depending on the value for the RecommendationProviderIdType property. This number determines how many recommended items are available for use in message variables. The minimum value is 1. The maximum value is 5. The default value is 5.</p> <p>To use multiple recommended items and custom attributes with message variables, you have to use an AWS Lambda function (RecommendationTransformerUri) to perform additional processing of recommendation data.</p>"
        }
      ]
    }
  },
  "required": [
    "RecommendationProviderUri",
    "RecommendationProviderRoleArn"
  ]
}

=== api-evangelist/amazon-pinpoint/examples/amazon-pinpoint-update-recommender-configuration-example.json
{
  "Attributes": "example-Attributes",
  "Description": "Description for Description",
  "Name": "Example Name",
  "RecommendationProviderIdType": "114586",
  "RecommendationProviderRoleArn": "303248",
  "RecommendationProviderUri": "603709",
  "RecommendationTransformerUri": "example-RecommendationTransformerUri",
  "RecommendationsDisplayName": "Example Recommendationsdisplayname",
  "RecommendationsPerMessage": "example-RecommendationsPerMessage"
}
